language: node_js
node_js:
- lts/*
deploy:
  provider: npm
  email: hectortosa@icloud.com
  api_key:
    secure: iSEUppMXOUaJvmlum34CEaIA+1izKyKlLxJSDdl5/I/zLe3+9KCGfgUwKoBvzGLc5vBJwnaOBDapJQchpWNWK+rhl1NQNKu3S3c9ViYrdLIybHVO7JqSPNWL2i3rnW1GzyTNFYWzyZWoe/1QyQx7Js+ysDT4HlTMLQmble0xzt+hSYYhgcbQoEefbzPLTjLW2OegEIMTK3GY8r68tKKBpv6U0SQOFqqlQQWHBEwmOWf6drQxBtV0WXODw3vLIYuP01JlJYO5LAoykBhtzuT9uzCz/f/onMDb2zylrq1i2tD18qYNY5apIiURY5YOnwHEo7FbSscJUgxq9/aWYN3oKP4jB92n7mgBk4QPVaw0SRZ6KOFN7p7iFTY8KLAwYQGWiCyJkRBRiMbb0mHKpVb3hvtQzozuQWMOuhfOo6PxNdDJLhDPDaVzzo9cOlkXed7BcNaNK6Ywo/+SvN1Aws1GIJxWufA6M5TNhPg/Tjwo81erT5pZFSqzBZF7IAyAQkimn2rf3Hv917HRIj3YKLDRuadqSLysOWdNMp7aj2v5vxSVxPKseYrxnfhYj1DvHfcFffWYXeIg3uix5RvnZz5ogLB6zL3s7rJmpjqbCGQfAD81V3CWZ6v4s6jp6oBoS6OW6yJuWfY42NFfzm3J7tI+fQexy3QTIys/CegSdzYSFN0=
  on:
    tags: true
    repo: hectortosa/shufflr
    branch: master
