name: JavaScript Build and Publish to Npm

on:
  push:
    branches:
      - trunk
    paths:
      - 'js/**'
jobs:
  build:
    name: Build, Test and Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./js
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
